/**
 * Programmers BattleGround -- Leaderboard UI
 *
 * DOM-based leaderboard component with two sections:
 *
 *   1. **Server Rating** -- loaded from `data/leaderboard.json` (results of
 *      overnight headless runs). This is the authoritative ranking.
 *
 *   2. **Current Battle** -- live stats from the in-browser simulation.
 *      Updated every tick via `updateLive()`.
 *
 * Both sections render as styled HTML tables that are injected into the
 * provided container elements.
 */

import type { InternalBrain } from '../types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Shape of a single entry in the live battle leaderboard. */
interface LeaderboardEntry {
  name: string;
  author: string;
  kills: number;
  deaths: number;
  iq: number;
  alive: boolean;
  color: string;
}

/** Shape of one record in data/leaderboard.json -> standings[]. */
interface ServerEntry {
  name: string;
  author: string;
  iq: number;
  kills: number;
  deaths: number;
}

/** Top-level shape of data/leaderboard.json. */
interface ServerLeaderboardData {
  lastUpdated: string;
  standings: ServerEntry[];
}

// ---------------------------------------------------------------------------
// Leaderboard
// ---------------------------------------------------------------------------

export class Leaderboard {
  private serverContainer: HTMLElement;
  private liveContainer: HTMLElement;
  private serverData: ServerEntry[] = [];
  private lastUpdated: string | null = null;

  constructor(serverContainer: HTMLElement, liveContainer: HTMLElement) {
    this.serverContainer = serverContainer;
    this.liveContainer = liveContainer;
    this.loadServerData();
  }

  // -------------------------------------------------------------------------
  // Server leaderboard
  // -------------------------------------------------------------------------

  /**
   * Fetch the server leaderboard JSON file. This is generated by overnight
   * headless runs and served as a static file.
   */
  private async loadServerData(): Promise<void> {
    try {
      const response = await fetch('./data/leaderboard.json');
      if (response.ok) {
        const data: ServerLeaderboardData = await response.json();
        this.serverData = data.standings || [];
        this.lastUpdated = data.lastUpdated || null;
        this.renderServerLeaderboard();
      }
    } catch {
      // Server data not available -- this is fine for local-only mode.
    }
  }

  /**
   * Render the server rating table into `serverContainer`.
   */
  private renderServerLeaderboard(): void {
    if (this.serverData.length === 0) {
      this.serverContainer.innerHTML = '';
      return;
    }

    const updatedStr = this.lastUpdated
      ? `<p class="leaderboard-updated">Updated: ${new Date(this.lastUpdated).toLocaleString()}</p>`
      : '';

    const rows = this.serverData
      .map(
        (entry, i) => `
        <tr>
          <td>${i + 1}</td>
          <td>${this.escapeHtml(entry.name)} <span class="author">(${this.escapeHtml(entry.author)})</span></td>
          <td class="right">${entry.kills}</td>
          <td class="right">${entry.deaths}</td>
          <td class="right">${entry.iq}</td>
        </tr>`,
      )
      .join('');

    this.serverContainer.innerHTML = `
      <div class="leaderboard-section">
        <h3>Server Rating</h3>
        ${updatedStr}
        <table class="leaderboard-table">
          <thead>
            <tr>
              <th>#</th>
              <th>NAME</th>
              <th>Ks</th>
              <th>Ds</th>
              <th>IQ</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    `;
  }

  // -------------------------------------------------------------------------
  // Live battle leaderboard
  // -------------------------------------------------------------------------

  /**
   * Update the live-battle leaderboard from the current brain states.
   *
   * @param brains       Array of all registered brains (alive and dead).
   * @param fullLeaderboard  When true, show all brains. When false, show
   *                         only those currently alive on the arena.
   */
  updateLive(brains: InternalBrain[], fullLeaderboard = false): void {
    const items: LeaderboardEntry[] = brains.map((b) => ({
      name: `${b.name} (${b.author})`.toUpperCase(),
      author: b.author,
      kills: b.kills,
      deaths: b.deaths,
      iq: b.iq,
      alive: b.alive,
      color: b.color,
    }));

    // Sort by IQ descending
    items.sort((a, b) => b.iq - a.iq);

    const rows = items
      .filter((item) => fullLeaderboard || item.alive)
      .slice(0, 20)
      .map((item, i) => {
        const cls = item.alive ? '' : ' class="dead"';
        const style = item.alive ? ` style="color:${item.color}"` : '';
        return `<tr${cls}${style}>
          <td>${i + 1}</td>
          <td>${this.escapeHtml(item.name)}</td>
          <td class="right">${item.kills}</td>
          <td class="right">${item.deaths}</td>
          <td class="right">${item.iq}</td>
        </tr>`;
      })
      .join('');

    this.liveContainer.innerHTML = `
      <div class="leaderboard-section">
        <h3>Current Battle</h3>
        <table class="leaderboard-table">
          <thead>
            <tr>
              <th>#</th>
              <th>NAME</th>
              <th>Ks</th>
              <th>Ds</th>
              <th>IQ</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    `;
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  /** Force a re-fetch of the server leaderboard data. */
  refresh(): void {
    this.loadServerData();
  }

  /**
   * Minimal HTML-entity escaping to prevent XSS from bot names/authors.
   */
  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
